### Login student
POST http://127.0.0.1:3001/user/login
Content-Type: application/json

{
    "email": "vinhnguyen@hcmut.edu.vn",
    "password": "12345634"
}


### Login admin
POST http://127.0.0.1:3001/user/login
Content-Type: application/json

{
    "email": "longnguyen@hcmut.edu.vn",
    "password": "12345634"
}


### Register users role student
POST http://127.0.0.1:3001/user/register
Content-Type: application/json

{
    "email": "vinhnguyen@hcmut.edu.vn",
    "password": "12345634",
    "mssv": "2015063",
    "faculty": "Computer",
    "fname": "Vinh Nguyen",
    "phone": "12345656",
    "role": "student"
}

### Error Register users role student email is not fomat University
POST http://127.0.0.1:3001/user/register
Content-Type: application/json

{
    "email": "vinhnguyen@hcmut.edu.",
    "password": "12345634",
    "mssv": "2015063",
    "faculty": "Computer",
    "fname": "Vinh Nguyen",
    "phone": "12345652",
    "role": "student"
}


### Register information user that exists email.
POST http://127.0.0.1:3001/user/register
Content-Type: application/json

{
    "email": "vinhnguyen@hcmut.edu.vn",
    "password": "12345634",
    "mssv": "2015063",
    "faculty": "Computer",
    "fname": "Vinh Nguyen",
    "phone": "1234565232",
    "role": "student"
}


### Register information user that exists mssv.
POST http://127.0.0.1:3001/user/register
Content-Type: application/json

{
    "email": "vinhnguyen@hcmut.edu.vn",
    "password": "12345634",
    "mssv": "2015063",
    "faculty": "Computer",
    "fname": "Vinh Nguyen",
    "phone": "12345652",
    "role": "student"
}


### Register users role admin
POST http://127.0.0.1:3001/user/register
Content-Type: application/json

{
    "email": "longnguyen@hcmut.edu.vn",
    "password": "12345634",
    "mssv": "2015063",
    "faculty": "Computer",
    "fname": "Vinh Nguyen",
    "phone": "12345652",
    "role": "admin"
}



### Add bank account
POST http://127.0.0.1:3001/user/addBankAccount
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGYyNTAwOTU2MGQzNjRiZDI5NjNlNyIsImlhdCI6MTczMzI0NDkwMiwiZXhwIjoxNzMzMjQ4NTAyfQ.oAQ2EBkAV7aW2JOZaebLfJyWywNSx3d-OI1GAvfJmxU

{
    "email": "longnguyen@hcmut.edu.vn",
    "bank_account": "12345634"
}





